---
platform: linux
image: docker:///boshcpi/vsphere-cpi-release
inputs:
  - name: bosh-cpi-release
  - name: stemcell
  - name: bats
  - name: vsphere-5.1-environment
run:
  path: bosh-cpi-release/ci/tasks/run-bats.sh
tags: ["vsphere"]
params:
  base_os:                                         replace-me
  network_type_to_test:                            replace-me
  BAT_STEMCELL_NAME:                               replace-me
  BAT_VLAN:                                        replace-me
  BAT_VCAP_PASSWORD:                               replace-me
  BAT_SECOND_NETWORK_VLAN:                         replace-me
  BOSH_SSH_PRIVATE_KEY:                            replace-me
  BOSH_VSPHERE_NTP_SERVER:                         replace-me
  BOSH_VSPHERE_NET_ID:                             replace-me
  BOSH_VSPHERE_VCENTER:                            replace-me
  BOSH_VSPHERE_VCENTER_USER:                       replace-me
  BOSH_VSPHERE_VCENTER_PASSWORD:                   replace-me
  BOSH_VSPHERE_VCENTER_DC:                         replace-me
  BOSH_VSPHERE_VCENTER_CLUSTER:                    replace-me
  BOSH_VSPHERE_VCENTER_RESOURCE_POOL:              replace-me
  BOSH_VSPHERE_VCENTER_DATASTORE_PATTERN:          replace-me
  BOSH_VSPHERE_VCENTER_UBOSH_DATASTORE_PATTERN:    replace-me
  BOSH_VSPHERE_VCENTER_FOLDER_PREFIX:              replace-me
